#!/usr/bin/env python3

from src.views.mail    import MailView
from src.views.main    import MainView
from src.views.tui     import TUI

from urwid import WidgetDisable, Filler

if __name__ == "__main__":

    main_view = MainView()
    tui       = TUI(Filler(main_view, valign="bottom"))

    main_view.connect("on_swap", lambda *x: tui.body(x[0]))

    # Add your views here
    main_view.add_views(
        [
            ("m", MailView(), "Mail"),
        ]
    )

    main_view.add_actions(
        [
            ("q", TUI.quit, "Quit"),
        ]
    )

    # End of time
    tui()
