#!/usr/bin/env python3

from src.clone import clone
from src.grade import grade
from src.assemble import assemble
from src.mail import Mail

choices = [
    clone,
    grade,
    assemble
]

choices_dict = {function.__name__: function for function in choices}

if __name__ == "__main__":
    print("Welcome to INF1900 interactive grading tool")

    while True:
        choice_list = list(choices_dict.keys())
        choice = input(f"What do you want to do? Please choose one of the following: {choice_list} ").strip()

        if choice in choices_dict:
            choices_dict[choice]()
        else:
            print("Incorrect parameter, please try again.")
